/**************************************************************************

DOSBase Version 1.5 Final
Copyright (C)1995-2000 Cliny Kennedy

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

DOSBase Website: http://revolutionaudio.dhs.org/dosbase

**************************************************************************/

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "structs.h"
#include "defs.h"

/* Refer To dosbase.c For Description Of These Global Variables */
extern const char* VERSION;
extern entry *front;
extern char sortMethod;
extern int entries;
extern char column_order;

/****************************************************************************
	htmlOut() is the routine which actually generates the HTML document.
	This function can be easily modified to change the appearance of the
	final HTML document (such as coloring, positioning, etc). 
****************************************************************************/
void htmlOut(FILE *fp)
{
	entry *current = front;
	char ch;

	if(current == NULL)
		return;

	/* Begin HTML document */
	fprintf(fp, "<HTML>\n");

	/* Write DOSBase comment */
	fprintf(fp, "\n<!-- This list was generated by %s\n", VERSION);
	fprintf(fp, "     (C)1999-2000 Clint Kennedy.  All Rights Reserved.\n");
	fprintf(fp, "     This comment is not to be removed.\n-->\n\n");

	/* Begin Head */
	fprintf(fp, "<HEAD>\n");
	fprintf(fp, "<TITLE>Current Mp3 List :: Generated By %s (C)1999-2000 Clint Kennedy</TITLE>\n", VERSION);
	fprintf(fp, "<META name=\"GENERATOR\" content=\"%s\">\n", VERSION);
	fprintf(fp, "</HEAD>\n\n");

	/* Begin Main Body */
	fprintf(fp, "<BODY vlink=\"#0000FF\" alink=\"#0000FF\" link=\"#0000FF\">\n\n");

	/* Print DOSBase Header */
	fprintf(fp, "<P align=\"center\"><FONT size=\"6\"><B>Current Mp3 List</B></FONT><BR>\n");
	fprintf(fp, "<FONT size=\"2\">Generated By <a href=\"http://revolutionaudio.dhs.org/dosbase\">%s</a> (C)1999-2000 Clint Kennedy</FONT>\n</P>\n\n", VERSION);

	/* Begin Navigation Section */
	fprintf(fp, "<P align=\"center\"><FONT size=\"4\"><B>Navigation</B><BR></FONT>\n\n");

	fprintf(fp, "<FONT size=\"2\"><A HREF=\"#09\">[0-9]</A> ");

	for (ch = 'A'; ch <= 'M'; ch++)
		fprintf(fp, "<A HREF=\"#%c\">[%c]</A> ", ch, ch);

	fprintf(fp, "<BR>\n");

	for (ch = 'N'; ch <= 'Z'; ch++)
		fprintf(fp, "<A HREF=\"#%c\">[%c]</A> ", ch, ch);

	fprintf(fp, "</FONT></P>\n\n<HR>\n\n");

	/* Process Entries */

	fprintf(fp, "<P><A name=\"09\"></A><FONT size=\"5\"><B>- 0-9 -</B></FONT>\n\n<BR>\n");

	current = front;
	switch(sortMethod)
	{
	case SORT_TITLE:
		while((stricmp(current->title, "A") < 0) && (current != NULL))
		{
			fprintf(fp, "%s - %s<BR>", current->title, current->artist);
			current = current->next;
			if(current == NULL) break;    /* Bug-fix in 1.5 */
		}
		break;   
	case SORT_ARTIST:
		while ((stricmp(current->artist, "A") < 0) && (current != NULL))
		{
			fprintf(fp, "%s - %s<BR>\n", current->artist, current->title);
			current = current->next;  
			if(current == NULL) break;     /* Bug-fix in 1.5 */
		}
		break;
	}

	fprintf(fp, "</P>\n");

	for (ch = 'A'; ch <= 'Z'; ch++)
	{
		fprintf(fp, "<P><A name=\"%c\"></A><FONT size=\"5\"><B>- %c -</B></FONT><BR>\n", ch, ch);
		current = front;
		switch(sortMethod)
		{
		case SORT_TITLE:
			while (current != NULL)
			{
				if(toupper(current->title[0]) == ch)
				fprintf(fp, "%s - %s<BR>\n", current->title, current->artist);
				current = current->next;
			}
			break;
		case SORT_ARTIST:
			while (current != NULL)
			{
				if(toupper(current->artist[0]) == ch)
				fprintf(fp, "%s - %s<BR>\n", current->artist, current->title);
				current = current->next;
			}            
			break;
		}
		fprintf(fp, "</P>\n");
	}

	/* End Body */
	fprintf(fp, "</BODY>\n\n");

	/* End Of HTML Document */
	fprintf(fp, "</HTML>\n");
}

/**********************************************************
txtout() generates columnar ASCII *.txt files.
It may easily be edited to change the format of the output.
**********************************************************/
void txtout(FILE* fp)
{
	entry *current = front;
                 
	fprintf(fp, "%s Generated List\n", VERSION);
	fprintf(fp, "(C)2000 Clint Kennedy.  All Rights Reserved.");
	fprintf(fp, "\n\nTotal Tracks Listed: %d", entries);

	switch (column_order)
	{
	case ARTIST_COLUMN_1ST:
		fprintf(fp, "\n\n");
		fprintf(fp, "%-50s%s\n", "Artist", "Title");
		fprintf(fp, "%-50s%s\n", "------", "-----");

		while (current != NULL)
		{
			fprintf(fp, "%-50s%s\n", current->artist, current->title);
			current = current->next;
		}
		break;
	case TITLE_COLUMN_1ST:
		fprintf(fp, "\n\n");
		fprintf(fp, "%-50s%s\n", "Title", "Artist");
		fprintf(fp, "%-50s%s\n", "-----", "------");
		while (current != NULL)
		{
			fprintf(fp, "%-50s%s\n", current->title, current->artist);
			current = current->next;
		}
		break;
	}
}